### ISSUE TITLE
Private and public dependencies

### ISSUE THREAD

**Issue by Mogball** [wio/wio#28]
```bash
[ 70%] Built target uno_CORE
[ 80%] Built target wlib-wio__2.1.3
Scanning dependencies of target wlib-json__1.0.3
[ 82%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonArray.cpp.obj
[ 84%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonCompare.cpp.obj
[ 85%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonElement.cpp.obj
[ 87%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonNull.cpp.obj
[ 89%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonObject.cpp.obj
[ 91%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonParse.cpp.obj
[ 92%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonStringify.cpp.obj
[ 94%] Building CXX object CMakeFiles/wlib-json__1.0.3.dir/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/src/wlib/wjson/JsonUtil.cpp.obj
[ 96%] Linking CXX static library libwlib-json__1.0.3.a
[ 96%] Built target wlib-json__1.0.3
Scanning dependencies of target tests
[ 98%] Building CXX object CMakeFiles/tests.dir/home/jeffniu/wlib-json/tests/main.cpp.obj
CMakeFiles/tests.dir/build.make:62: recipe for target 'CMakeFiles/tests.dir/home/jeffniu/wlib-json/tests/main.cpp.obj' failed
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/tests.dir/all' failed
Makefile:83: recipe for target 'all' failed
failure
Error Report:
In file included from /home/jeffniu/wlib-json/tests/main.cpp:4:0:
/home/jeffniu/wlib-json/.wio/pkg_module/wlib-json/include/wlib/wjson/JsonElement.h:4:23: fatal error: wlib/string: No such file or directory
 #include <wlib/string>
                       ^
compilation terminated.
make[2]: *** [CMakeFiles/tests.dir/home/jeffniu/wlib-json/tests/main.cpp.obj] Error 1
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
make: *** [all] Error 2
exit status 2
```

So `wlib-json` includes `wlib-wio` and compiles, but when `wlib-json` headers that include `wlib-wio` headers are included in the target that does NOT define `wlib-wio` as a immediate dependency the build fails because `wlib-wio` is not added to the target path. 

So we can have a "public" dependency system where `wlib-wio` is declared a public dependency of `wlib-json` since one of its headers is included in one of `wlib-json`'s public headers.

And vice versa if a dependency is marked "public" but none of its headers are included in a public header of the current package.

`wio` can also scan files and give a warning to people who include dependency headers in a public header but did not mark them as a public dependency. I.e. I include `<wlib/string>` in `<wlib/json>` but did not mark `wlib-wio` as a public dependency.

**Comment by Mogball** [comment]
Jk I can't even build my test target

```yaml
pkg:
  name: wlib-json
  description: JSON library for wio
  repository: https://github.com/waterloop/wlib-json.git
  version: 1.0.3
  author: Jeff Niu <jeffniu22@gmail.com> (https://github.com/mogball)
  contributors: []
  organization: Waterloop
  keywords:
  - wio
  - c
  - c++
  - json
  - waterloop
  license: MIT
  header_only: false
  platform: ALL
  framework:
  - ALL
  board:
  - ALL
  - uno
  allow_only_global_flags: false
  allow_only_required_flags: false
  global_flags: []
  required_flags: []
  included_flags: []
  ide: none

targets:
  default: tests
  create:
    tests:
      board: uno
      target_flags: []
      global_flags: []
      pkg_flags: []

dependencies:
  wlib-wio:
    version: 2.1.3
    vendor: false

    dependency_flags:
    - -DMAX_ALLOCATORS=10u
    - -DNUM_BLOCKS=400u
```

Since I don't know how to specify that `wio` should link `wlib-wio` to `tests`

**Comment by Mogball** [comment]
here's the generated CMakeLists.txt

```cmake
set(CMAKE_VER 3.0.0)
set(PROJECT_NAME wlib-json)
set(PROJECT_PATH "/home/jeffniu/wlib-json")
set(CMAKE_TOOLCHAIN_PATH "/home/jeffniu/external/wio/bin")
set (CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
set(DEPENDENCY_FILE dependencies)

# all the paths toolchain can be at (this is because of different package managers)
if (EXISTS "${CMAKE_TOOLCHAIN_PATH}/toolchain/cmake/CosaToolchain.cmake")
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_PATH}/toolchain/cmake/CosaToolchain.cmake")
elseif (EXISTS "${CMAKE_TOOLCHAIN_PATH}/../toolchain/cmake/CosaToolchain.cmake")
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_PATH}/../toolchain/cmake/CosaToolchain.cmake")
elseif (EXISTS "/usr/share/wio/toolchain/cmake/CosaToolchain.cmake")
    set(CMAKE_TOOLCHAIN_FILE "/usr/share/wio/toolchain/cmake/CosaToolchain.cmake")
else()
    message(FATAL_ERROR "Toolchain cannot be found. Build Halted!")
endif()

# properties
set(TARGET_NAME tests)
set(BOARD uno)
set(FRAMEWORK ALL)
set(ENTRY tests)

cmake_minimum_required(VERSION ${CMAKE_VERSION})
project(${PROJECT_NAME} C CXX ASM)
cmake_policy(SET CMP0023 OLD)

file(GLOB_RECURSE SRC_FILES "${PROJECT_PATH}/${ENTRY}/*.cpp" "${PROJECT_PATH}/${ENTRY}/*.cc" "${PROJECT_PATH}/${ENTRY}/*.c")
generate_arduino_firmware(${TARGET_NAME}
    SRCS ${SRC_FILES}
    BOARD ${BOARD}
    PORT )
target_compile_definitions(${TARGET_NAME} PRIVATE __AVR_${FRAMEWORK}__ )


include(${DEPENDENCY_FILE})
```

Neither `wlib-json` nor `wlib-wio` are even linked to the test target. Please test your fucking versions lol

**Comment by dhillondeep** [comment]
it is all done in `dependencies.cmake` lol

**Comment by dhillondeep** [comment]
It will link `wlib-wio` to `wlib-json` and not to the target. In `app` type, you can specify the link to both `wlib-wio` and `wlib-json`. Let me try this one sec

**Comment by dhillondeep** [comment]
`wio` works as intended. It links `wlib-wio` to `wlib-json` and not to the target. What you are asking for is `dev_dependencies`. We should add them soon. It should not be too hard

**Comment by Mogball** [comment]
Yeah but I need to compile my test target

**Comment by Mogball** [comment]
It's part of the build verification lol

**Comment by Mogball** [comment]
It isn't dev dependencies I want to compile my test target in the package and the libraries aren't linked to it at all

**Comment by dhillondeep** [comment]
what is your dependencies.cmake file?

**Comment by dhillondeep** [comment]
wio will make `wlib-json` as a package and link that to your `test` target in dependencies.cmake

**Comment by dhillondeep** [comment]
The issue is this
```cmake
target_link_libraries(wlib-json__0.0.1 PRIVATE wlib-wio__2.1.3)
```
The linking is PRIVATE by default and there is an issue when someone include wlib-json.

We can add an option in dependencies to specify if the linking has to be `PUBLIC` or `PRIVATE`

**Comment by Mogball** [comment]
dependencies.cmake has no mention of the tests target, also it's not just library linking the tests target needs the include path as well

**Comment by dhillondeep** [comment]
It is fixed now you can test. Your `wio.yml` should look like this:
```yaml
pkg:
  name: wlib-json
  description: JSON library for wio
  repository: https://github.com/waterloop/wlib-json.git
  version: 1.0.3
  author: Jeff Niu <jeffniu22@gmail.com> (https://github.com/mogball)
  contributors: []
  organization: Waterloop
  keywords:
  - wio
  - c
  - c++
  - json
  - waterloop
  license: MIT
  header_only: false
  platform: ALL
  framework:
  - ALL
  board:
  - ALL
  - uno
  allow_only_global_flags: false
  allow_only_required_flags: false
  global_flags: []
  required_flags: [-DMAX_ALLOCATORS, -DNUM_BLOCKS]
  included_flags: []
  ide: none

targets:
  default: tests
  create:
    tests:
      board: uno
      target_flags: []
      global_flags: []
      pkg_flags:
      - -DMAX_ALLOCATORS=10u
      - -DNUM_BLOCKS=400u

dependencies:
  wlib-wio:
    version: 2.1.3
    vendor: false
    link_visibility: "PUBLIC"
    dependency_flags: [$(-DMAX_ALLOCATORS), $(-DNUM_BLOCKS)]

```
